export default() => {
    let data = {
        "domain":{
           "domainId":"FINANCE"
        },
        "mclass":{
           "classId":"SECTOR",
           "message":"업종"
        },
        "msections":[
           {
              "sectionId":"BASIC",
              "dispSeq":"1",
              "isEnable":"Y",
              "message":"기본정보",
              "mgroups":[
                 {
                    "groupId":"STANDARD",
                    "dispSeq":"1",
                    "isEnable":"Y",
                    "message":"표준 속성",
                    "props":[
                       {
                          "propId":"EVENT_CODE",
                          "areaId":"*",
                          "type":"STRN",
                          "unit":"",
                          "width":"100",
                          "regex":"",
                          "ruleCode":"",
                          "mask":"",
                          "dbType":"VARCHAR(100)",
                          "message":"종목코드",
                          "value":"Test",
                          "reference":"",
                          "propMode":null,
                          "options":{
                             "propMode":null,
                             "isDisabled":"N",
                             "isReadOnly":"N",
                             "isShow":"Y",
                             "dispSeq":"10"
                          }
                       },
                       {
                        "propId":"EVENT_NUMBER",
                        "areaId":"*",
                        "type":"NVAL",
                        "unit":"NO",
                        "width":"100",
                        "regex":"",
                        "ruleCode":"",
                        "mask":"",
                        "dbType":"VARCHAR(100)",
                        "message":"종목번호",
                        "value": 0,
                        "reference":"",
                        "propMode":null,
                        "options":{
                           "propMode":null,
                           "isDisabled":"N",
                           "isReadOnly":"N",
                           "isShow":"Y",
                           "dispSeq":"10"
                        }
                     },
                       {
                          "propId":"ETC_FILE",
                          "areaId":"*",
                          "type":"FILE",
                          "unit":"",
                          "width":"100",
                          "regex":"",
                          "ruleCode":"",
                          "mask":"",
                          "dbType":"VARCHAR(100)",
                          "message":"일반 파일",
                          "reference":"",
                          "propMode":null,
                          "options":{
                             "propMode":null,
                             "isDisabled":"N",
                             "isReadOnly":"N",
                             "isShow":"Y",
                             "dispSeq":"15"
                          }
                       },
                       {
                          "propId":"CODE_REF",
                          "areaId":"*",
                          "type":"CODE",
                          "unit":"",
                          "width":"150",
                          "regex":"",
                          "ruleCode":"",
                          "mask":"",
                          "dbType":"VARCHAR(100)",
                          "message":"코드 테스트",
                          "reference":"LANGAUGE",
                          "value": "KO",
                          "propMode":null,
                          "options":{
                             "propMode":null,
                             "isDisabled":"N",
                             "isReadOnly":"N",
                             "isShow":"Y",
                             "dispSeq":"12"
                          }
                       }
                    ]
                 }
              ]
           }
        ]
     }
    return data
}